language: objective-c
osx_image: xcode9.4
xcode_project: MathSwift.xcodeproj
xcode_scheme: MathSwift

branches:
  only:
  - master
  - development
script: xcodebuild test -project MathSwift.xcodeproj -scheme MathSwift -destination "OS=11.4,name=iPhone X" -configuration Release
